#!/bin/bash

#online-judge-toolsコマンドを利用して、atcoderのテストサンプルを一括ダウンロードする
#usage: ojd contestid
cid=$1
mkdir -p $cid/{A..E}

for dir in {A..E}
do
  oj download -d "${cid}/${dir}/test" "https://atcoder.jp/contests/${cid}/tasks/${cid}_${dir,}"
done
